export const START_NEW_GAME = 'START_NEW_GAME';
export const START_NEW_ROUND = 'START_NEW_ROUND';
export const WIN_GAME = 'WIN_GAME';
export const LOSE_GAME = 'LOSE_GAME';

export const SET_QUEUE_INDEX = 'SET_QUEUE_INDEX';
export const INCREMENT_QUEUE_INDEX = 'INCREMENT_QUEUE_INDEX';
export const SET_GAME_STATE = 'SET_GAME_STATE';
export const SET_PLAYER_INTERRUPT = 'SET_PLAYER_INTERRUPT';
export const SET_ACTIVE_HERO = 'SET_ACTIVE_HERO';
export const QUEUE_ACTION = 'QUEUE_ACTION';

export const SET_GROUP_MESSAGE = 'SET_GROUP_MESSAGE';
export const SET_ENTITY_STATUS = 'SET_ENTITY_STATUS';
export const SET_ENTITY_ANIMATION = 'SET_ENTITY_ANIMATION';
export const ENTITY_DAMAGE = 'ENTITY_DAMAGE';
