export enum EntityTypesEnum {
  HERO = 'HERO',
  MONSTER = 'MONSTER',
  ROBOT = 'ROBOT',
}

export enum GameStatesEnum {
  INIT = 'INIT',
  GAME_WON = 'GAME_WON',
  GAME_LOST = 'GAME_LOST',
  PLAYER_INPUT = 'PLAYER_INPUT',
  EXECUTING_ACTION = 'EXECUTING_ACTION',
  AI_EXECUTING = 'AI_EXECUTING',
  POST_EXECUTION = 'POST_EXECUTION',

  EXECUTING = 'EXECUTING',
  INTERRUPT = 'INTERRUPT',
}
